# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#default

gui:
  theme:
    activeBorderColor:
      - red
      - bold
    inactiveBorderColor:
      - "#505050"
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - "#404040"
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never

services:
  'github.com': 'github:github.com'
  'gitlab-app.eng.qops.net': 'gitlab:gitlab-app.eng.qops.net'

os:
  edit: "nvim {{filename}}"
  editAtLine: "nvim +{{line}} {{filename}}"
